title: Moore's Treasury
description: A commonplace book
url: https://moorestreasury.com
baseurl: ""
markdown: kramdown

collections:
  entries:
    output: true
    permalink: /entries/:name/
  commonplaces:
    output: true
    permalink: /commonplaces/:title/
